name: first-time-setup
run-name: first time setup of repo

on:
  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write

jobs:
  first-time-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Debug dump
        if: runner.debug == '1'
        uses: crazy-max/ghaction-dump-context@v2

      - name: Create Pages branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "gh-pages"

      - name: Checkout Pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      # clean slate, as if starting from orphan branch
      - name: Clear Pages branch
        run: rm -rf ./* .github .docker .gitignore

      # prevent GitHub from running Jekyll a second time after build
      - name: Make .nojekyll file
        run: touch .nojekyll

      - name: Commit changes to Pages branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: "Clear branch"

